### ISSUE TITLE
git-lfs not allowed on public forks

### ISSUE THREAD

**Issue by davecampbell** [butchland/fastai-binder-app-template#1]
seems to be a policy on github.
after making the fork, it can be renamed, and then a new blank one created with the same name (fastai-binder-app-template).
then the 'git push' works, and invokes git-lfs perfectly.

original error:
`batch response: @davecampbell can not upload new objects to public fork davecampbell/fastai-binder-app-template   
error: failed to push some refs to 'git@github.com:davecampbell/fastai-binder-app-template.git'`

**Comment by butchland** [comment]
Thanks for the comment, Dave!

Yeah I found [this issue in git-lfs ](https://github.com/git-lfs/git-lfs/issues/1906)which makes it (I think) more of a policy than a bug (its enabled in Github's enterprise edition) . 

I'll update the docs to mention this issue.

Best regards,
Butch
